---
# gitaly-pv.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitaly-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /Users/yuri/DATA/SANDBOX/gitaly/data
